### ISSUE TITLE
Repo update?

### ISSUE THREAD

**Issue by Eisen-Hardt** [Largehawiian/SonicwallAPI#1]
Hi there, I'm interested in your module and may be interested in making some contributions but it seems your repo here is out of date compared to what is hosted on powershellgallery.com.

Would you update this repo and hopefully keep this the source of truth, so to speak?

Thanks

**Comment by Largehawiian** [comment]
I will check into it. It's kind of been on the back burner for awhile, which literally every person on github says when their repo is out of date :) 
I will see what I can do to get it updated / cleaned up and published.
Thank you for your interest in the Sonicwall API module

**Comment by Eisen-Hardt** [comment]
Alright, thank you Largehawiian I appreciate the fast response. I found the SonicOS API reference the other day and wanted to build some powershell around it, and I figured that someone probably already did that ;)
